name: Flask App Workflow
 
on:
  push:
    branches: [main]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install flask
      - name: Run Flask app
        run: flask run --host=0.0.0.0
